# .github/workflows/app.yaml
name: Prices Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'models/prices/prices_tokens.sql'
  push:
    branches:
      - 'main'

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prices-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: Fetch base commit
        run:  git fetch origin ${{ github.event.pull_request.base.sha }}

      - name: Fetch head commit
        run: git fetch origin ${{ github.event.pull_request.head.sha }}

      - name: Get prices diff
        shell: bash
        run: |
          git diff ${{ github.event.pull_request.base.sha}}..${{ github.event.pull_request.head.sha }} models/prices/prices_tokens.sql | grep '^\+ ' > other.txt

      - name: Test Variable
        run: cat other.txt

      - name: Run validations
        working-directory: scripts
        run: python token_checker.py --new_lines $PRICES_DIFF 2>&1